### ISSUE TITLE
Creating Custom Lens that pulls data from an API.

### ISSUE THREAD

**Issue by shirazz** [alpertuna/react-lens#1]
I would like to know how i can get a data from an API response and append it with the `content`. I have a `product-card` component which have a `price`. The currency is dependent on store settings. This settings is being pulled from an API.  I tried using the `make` function interface. Any inputs are always welcome.

**Comment by alpertuna** [comment]
Hello @shirazz,
Actually I didn't got the appending with the content point. But for other part, you can achieve it by wrapping existing `currency` support like this.
```javascript
// File: Price.jsx
import React from 'react';
import Lens from 'react-lens';
const parameters = getCurrencyParametersForLensSomehow(); // It may returns '$ : 2' from storage;

export default (props) => (
  <Lens filter={`currency : ${parameters}`}>{props.children}</Lens>
);
```
And you can use this wrapper like this;
```javascript
import React from 'react';
import Price from './price';

const price = 5.4;
<Price>{price}</Price>;
```
